[options]
admin_passwd = admin
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo14_test
addons_path = c:\Users\marcos\Desktop\Odoo\odoo_14.0\addons,c:\Users\marcos\Desktop\Odoo\odoo_14.0\custom_addons
http_port = 8014
log_level = info
